apiVersion: v1
kind: Service
metadata:
  name: {{ template "ladarr.fullname" . }}
  labels:
    app: {{ template "ladarr.name" . }}
    chart: {{ template "ladarr.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7878
      protocol: TCP
      name: http
  selector:
    app: {{ template "ladarr.name" . }}
    release: {{ .Release.Name }}
